<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\BoxOffice.DAL\BoxOffice.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
  </ItemGroup>
	
</Project>
