// <auto-generated />
using System;
using BoxOffice.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxOffice.DAL.Migrations
{
    [DbContext(typeof(BoxOfficeDbContext))]
    [Migration("20251216152600_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "William Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Anton Chekhov"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Tennessee Williams"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Arthur Miller"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Friedrich Schiller"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Molière"
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BookedAt")
                        .HasColumnType("date")
                        .HasColumnName("booked_at");

                    b.Property<string>("BookingToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.ToTable("bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-bbbb-cccc-dddddddddddd"),
                            BookedAt = new DateOnly(2024, 2, 9),
                            BookingToken = "BOOK123456",
                            ExpiresAt = new DateOnly(2024, 2, 12),
                            State = "Active",
                            TicketId = new Guid("22222222-2222-2222-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-cccc-dddd-eeeeeeeeeeee"),
                            BookedAt = new DateOnly(2024, 1, 28),
                            BookingToken = "BOOK654321",
                            ExpiresAt = new DateOnly(2024, 1, 31),
                            State = "Expired",
                            TicketId = new Guid("55555555-5555-5555-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "john.smith@example.com",
                            Name = "John Smith",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "emma.johnson@example.com",
                            Name = "Emma Johnson",
                            Phone = "+1-555-0102"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            Email = "michael.brown@example.com",
                            Name = "Michael Brown",
                            Phone = "+1-555-0103"
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            Email = "sarah.davis@example.com",
                            Name = "Sarah Davis",
                            Phone = "+1-555-0104"
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Email = "robert.wilson@example.com",
                            Name = "Robert Wilson",
                            Phone = "+1-555-0105"
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Tragedy"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Historical"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Absurd"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Satire"
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Poster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("performance_author");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("performance_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_name");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_venue");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("posters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            AuthorId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Date = new DateOnly(2024, 3, 15),
                            Description = "A tragedy about the Prince of Denmark seeking revenge for his father's murder",
                            Duration = 180,
                            Name = "Hamlet",
                            Venue = "Royal Shakespeare Theatre"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            AuthorId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Date = new DateOnly(2024, 2, 14),
                            Description = "The classic story of two young star-crossed lovers",
                            Duration = 150,
                            Name = "Romeo and Juliet",
                            Venue = "Globe Theatre"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            AuthorId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Date = new DateOnly(2024, 4, 20),
                            Description = "A play about the romantic and artistic conflicts between four characters",
                            Duration = 140,
                            Name = "The Seagull",
                            Venue = "Moscow Art Theatre"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            AuthorId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Date = new DateOnly(2024, 5, 10),
                            Description = "The story of an aristocratic Russian family forced to sell their estate",
                            Duration = 160,
                            Name = "The Cherry Orchard",
                            Venue = "Bolshoi Theatre"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            AuthorId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Date = new DateOnly(2024, 6, 5),
                            Description = "The story of Blanche DuBois and her conflicts with her brother-in-law",
                            Duration = 155,
                            Name = "A Streetcar Named Desire",
                            Venue = "Broadway Theatre"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            AuthorId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Date = new DateOnly(2024, 7, 1),
                            Description = "The tragedy of Willy Loman, a traveling salesman",
                            Duration = 165,
                            Name = "Death of a Salesman",
                            Venue = "National Theatre"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            AuthorId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Date = new DateOnly(2024, 8, 15),
                            Description = "A comedy about Harpagon and his obsessive greed",
                            Duration = 135,
                            Name = "The Miser",
                            Venue = "Comédie-Française"
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seat_number");

                    b.Property<DateOnly?>("SoldDate")
                        .HasColumnType("date")
                        .HasColumnName("sold_date");

                    b.Property<Guid>("TicketInfoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_info");

                    b.Property<string>("TicketState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[booking] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketInfoId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-aaaa-aaaaaaaaaaaa"),
                            CustomerId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SeatNumber = "A101",
                            SoldDate = new DateOnly(2024, 2, 10),
                            TicketInfoId = new Guid("aaaaaaaa-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            TicketState = "Sold"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-bbbb-bbbbbbbbbbbb"),
                            BookingId = new Guid("aaaaaaaa-1111-bbbb-cccc-dddddddddddd"),
                            CustomerId = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SeatNumber = "V001",
                            TicketInfoId = new Guid("aaaaaaaa-2222-bbbb-bbbb-bbbbbbbbbbbb"),
                            TicketState = "Booked"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-cccc-cccccccccccc"),
                            CustomerId = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            SeatNumber = "A102",
                            SoldDate = new DateOnly(2024, 2, 11),
                            TicketInfoId = new Guid("aaaaaaaa-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            TicketState = "Sold"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-dddd-dddddddddddd"),
                            CustomerId = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            SeatNumber = "B201",
                            SoldDate = new DateOnly(2024, 1, 25),
                            TicketInfoId = new Guid("bbbbbbbb-1111-cccc-cccc-cccccccccccc"),
                            TicketState = "Sold"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-eeee-eeeeeeeeeeee"),
                            BookingId = new Guid("bbbbbbbb-2222-cccc-dddd-eeeeeeeeeeee"),
                            CustomerId = new Guid("55555555-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SeatNumber = "C301",
                            TicketInfoId = new Guid("cccccccc-1111-dddd-dddd-dddddddddddd"),
                            TicketState = "Booked"
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.TicketInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("int")
                        .HasColumnName("available_tickets");

                    b.Property<int>("BookedCount")
                        .HasColumnType("int")
                        .HasColumnName("booked_tickets");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("poster");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("price");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("sold_tickets");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("type");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int")
                        .HasColumnName("total_tickets");

                    b.HasKey("Id");

                    b.HasIndex("PosterId");

                    b.ToTable("ticket_infos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            AvailableCount = 0,
                            BookedCount = 0,
                            PosterId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Price = 1500m,
                            SoldCount = 2,
                            TicketType = "Economy",
                            TotalCount = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-bbbb-bbbb-bbbbbbbbbbbb"),
                            AvailableCount = 0,
                            BookedCount = 1,
                            PosterId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Price = 4000m,
                            SoldCount = 0,
                            TicketType = "VIP",
                            TotalCount = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-cccc-cccc-cccccccccccc"),
                            AvailableCount = 0,
                            BookedCount = 0,
                            PosterId = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Price = 1200m,
                            SoldCount = 1,
                            TicketType = "Economy",
                            TotalCount = 1
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-dddd-dddd-dddddddddddd"),
                            AvailableCount = 0,
                            BookedCount = 1,
                            PosterId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Price = 1000m,
                            SoldCount = 0,
                            TicketType = "Economy",
                            TotalCount = 1
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketId");

                    b.ToTable("transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-dddddddddddd"),
                            Amount = 1500m,
                            CustomerId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Date = new DateOnly(2024, 2, 10),
                            PaymentMethod = "CardOnline",
                            TicketId = new Guid("11111111-1111-1111-aaaa-aaaaaaaaaaaa"),
                            TransactionType = "Purchase"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Amount = 1500m,
                            CustomerId = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            Date = new DateOnly(2024, 2, 11),
                            PaymentMethod = "CashAtVenue",
                            TicketId = new Guid("33333333-3333-3333-cccc-cccccccccccc"),
                            TransactionType = "Purchase"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-dddd-eeee-ffffffffffff"),
                            Amount = 1200m,
                            CustomerId = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            Date = new DateOnly(2024, 1, 25),
                            PaymentMethod = "CardAtVenue",
                            TicketId = new Guid("44444444-4444-4444-dddd-dddddddddddd"),
                            TransactionType = "Purchase"
                        });
                });

            modelBuilder.Entity("poster_genres", b =>
                {
                    b.Property<Guid>("poster_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("genre_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("poster_id", "genre_id");

                    b.HasIndex("genre_id");

                    b.ToTable("poster_genres");

                    b.HasData(
                        new
                        {
                            poster_id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            genre_id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            poster_id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            genre_id = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            poster_id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            genre_id = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            poster_id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            genre_id = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            poster_id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            genre_id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            poster_id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            genre_id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            poster_id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            genre_id = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            poster_id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            genre_id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            poster_id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            genre_id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            poster_id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            genre_id = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            poster_id = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            genre_id = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            poster_id = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            genre_id = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Poster", b =>
                {
                    b.HasOne("BoxOffice.DAL.Models.Entities.Author", "Author")
                        .WithMany("Posters")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Ticket", b =>
                {
                    b.HasOne("BoxOffice.DAL.Models.Entities.Booking", "Booking")
                        .WithOne("Ticket")
                        .HasForeignKey("BoxOffice.DAL.Models.Entities.Ticket", "BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxOffice.DAL.Models.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxOffice.DAL.Models.Entities.TicketInfo", "TicketInfo")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("TicketInfo");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.TicketInfo", b =>
                {
                    b.HasOne("BoxOffice.DAL.Models.Entities.Poster", "Poster")
                        .WithMany("TicketInfos")
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Transaction", b =>
                {
                    b.HasOne("BoxOffice.DAL.Models.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Models.Entities.Ticket", "Ticket")
                        .WithMany("Transactions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("poster_genres", b =>
                {
                    b.HasOne("BoxOffice.DAL.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Models.Entities.Poster", null)
                        .WithMany()
                        .HasForeignKey("poster_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Author", b =>
                {
                    b.Navigation("Posters");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Booking", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Poster", b =>
                {
                    b.Navigation("TicketInfos");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.Ticket", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Models.Entities.TicketInfo", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
