// <auto-generated />
using System;
using BoxOffice.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxOffice.DAL.Migrations
{
    [DbContext(typeof(BoxOfficeDbContext))]
    [Migration("20251212013330_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxOffice.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("author_name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("BookingToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("booking_token");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate");

                    b.HasIndex("BookingToken")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_phone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("poster_description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("performance_duration");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poster_genres");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("poster_name");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("performance_venue");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("posters");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BookedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("booked_until");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("poster_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seat_number");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sold_date");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ticket_state");

                    b.Property<Guid>("TicketInfoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_info_id");

                    b.Property<string>("UniqueBookingToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unique_booking_token");

                    b.HasKey("Id");

                    b.HasIndex("BookedUntil");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PosterId");

                    b.HasIndex("SoldDate");

                    b.HasIndex("State");

                    b.HasIndex("TicketInfoId");

                    b.HasIndex("PosterId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int")
                        .HasColumnName("available_tickets");

                    b.Property<int>("BookedTickets")
                        .HasColumnType("int")
                        .HasColumnName("booked_tickets");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("poster_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ticket_price");

                    b.Property<int>("SoldTickets")
                        .HasColumnType("int")
                        .HasColumnName("sold_tickets");

                    b.Property<int>("TicketType")
                        .HasColumnType("int")
                        .HasColumnName("ticket_type");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int")
                        .HasColumnName("total_tickets");

                    b.HasKey("Id");

                    b.HasIndex("PosterId");

                    b.HasIndex("TicketType");

                    b.ToTable("tickets_info");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Card")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("payment_reference");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Booking", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Author", "Author")
                        .WithMany("Posters")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Ticket", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxOffice.DAL.Entities.Customer", "Customer")
                        .WithMany("PurchasedTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BoxOffice.DAL.Entities.Poster", "Poster")
                        .WithMany("Tickets")
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Entities.TicketInfo", "TicketInfo")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Poster");

                    b.Navigation("TicketInfo");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Poster", "Poster")
                        .WithMany("TicketInfos")
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Transaction", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Author", b =>
                {
                    b.Navigation("Posters");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PurchasedTickets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.Navigation("TicketInfos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
