// <auto-generated />
using System;
using BoxOffice.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxOffice.DAL.Migrations
{
    [DbContext(typeof(BoxOfficeDbContext))]
    partial class BoxOfficeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxOffice.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BookedAt")
                        .HasColumnType("date")
                        .HasColumnName("booked_at");

                    b.Property<string>("BookingToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("performance_author");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("performance_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_name");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performance_venue");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("posters");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seat_number");

                    b.Property<DateOnly?>("SoldDate")
                        .HasColumnType("date")
                        .HasColumnName("sold_date");

                    b.Property<Guid>("TicketInfoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_info");

                    b.Property<string>("TicketState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[booking] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketInfoId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("int")
                        .HasColumnName("available_tickets");

                    b.Property<int>("BookedCount")
                        .HasColumnType("int")
                        .HasColumnName("booked_tickets");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("poster");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("price");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("sold_tickets");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("type");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int")
                        .HasColumnName("total_tickets");

                    b.HasKey("Id");

                    b.HasIndex("PosterId");

                    b.ToTable("ticket_infos");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("poster_genres", b =>
                {
                    b.Property<Guid>("poster_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("genre_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("poster_id", "genre_id");

                    b.HasIndex("genre_id");

                    b.ToTable("poster_genres");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Author", "Author")
                        .WithMany("Posters")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Ticket", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Booking", "Booking")
                        .WithOne("Ticket")
                        .HasForeignKey("BoxOffice.DAL.Entities.Ticket", "BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxOffice.DAL.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxOffice.DAL.Entities.TicketInfo", "TicketInfo")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("TicketInfo");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Poster", "Poster")
                        .WithMany("TicketInfos")
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Transaction", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Entities.Ticket", "Ticket")
                        .WithMany("Transactions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("poster_genres", b =>
                {
                    b.HasOne("BoxOffice.DAL.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoxOffice.DAL.Entities.Poster", null)
                        .WithMany()
                        .HasForeignKey("poster_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Author", b =>
                {
                    b.Navigation("Posters");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Booking", b =>
                {
                    b.Navigation("Ticket")
                        .IsRequired();
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Poster", b =>
                {
                    b.Navigation("TicketInfos");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.Ticket", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BoxOffice.DAL.Entities.TicketInfo", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
